spring:
   data:
     mongodb:
       host: ds113746.mlab.com
       port: 13746
       database: lab07
       username: admin
       password: admin
redis:
   host: 127.0.0.1
   #host: 192.168.56.101
   port: 6379
